### ISSUE TITLE
Exporting Components interface

### ISSUE THREAD

**Issue by Gussi** [hacked/irc#1]
Would it be appropriate to export the Components interface? I'm creating my own client, and had to create my own Components interface internally so I could explicitly type method parameters and return values when I'm passing messages around.

I'm new to Deno and TS in general, so maybe I'm just using it wrong, but I feel like I'm duplicating knowledge by essentially re-declaring my own Components interface.

**Comment by hacked** [comment]
That's a good point, the `Components` interface should be exported as well, I'll submit a PR in a bit.

Thanks for letting me know!

**Comment by hacked** [comment]
I exported the interface (#2) and tagged a new release.
You can now use version 1.0.1, `https://deno.land/x/irc@1.0.1/mod.ts`.

Hope it helps, feel free to suggest other improvements.

**Comment by Gussi** [comment]
Excellent, thanks for this.
